### ISSUE TITLE
Please support PHP 5.3

### ISSUE THREAD

**Issue by praveenbm5** [dsx724/php-bloom-filter#1]
Most of the current stable repositories contain PHP 5.3 and requiring 5.4 out of box is a deal breaker for many of us who want to use this library.

Changing the deployment stack is beyond the reach of developers in many companies.

Thank you.

**Comment by dsx724** [comment]
The change to support PHP 5.3 is two lines:
$hash_sub = hexdec(unpack('H_',substr($hash,$index_$this->chunk_size,$this->chunk_size))[1]) & $this->mask;

Save unpack('H_',substr($hash,$index_$this->chunk_size,$this->chunk_size)) to a variable and then use $variable[1] for hexdec.  If you need explicit code for this, let me know.

**Comment by praveenbm5** [comment]
May be you can branch out for 5.3 for easy maintainability. 

One more thing...

The class currently does not have semantics for storage and retrieval (export and import) of Bloom filters. We can use object serialize and unserialize but that will become php bound representation. For many use cases we might need to store the state of a bloom filter in database or file for later use.

Eg. We are planning to use bloom filters for voting. So each entity recieving votes will have a bloom filter and every time a user votes we add him to the BF. This way we can ensure that no one person can vote multiple times and jack up the count. The count we need is also fuzzy so we dont need exact number of votes. Just enough to say something is popular, mediocre or bad.

I was also wondering if we can infer the popularity from the bloom filter itself with out having a separate counter. Something like the number of bits in the BF that are currently 1 can infer the popularity. Obviously the count will go up as more people vote for that entity.

**Comment by dsx724** [comment]
Check out the php-legacy branch and test it (test.php) in a PHP 5.3 install.  All my own servers have 5.4 via PPA already so I cannot test it.

As for serialization facilities, you can add a function that uses file_put_contents or a database call and store the bit-array as well as the associated n,m,k,hash.  I will implement a file based import and export but you are on you own as to the database store.  These bloom filters can get extremely large (1GB) so I don't understand how you plan to use them in the PHP lifecycle but I would suggest opening a socket on PHP and do an loop on external requests instead of loading the bloom filter every time.

**Comment by praveenbm5** [comment]
If we want lesser probability for false positives then BF size can grow. But for our purpose may be a 256bit/512bit BF will suffice I guess. In that case using them as part of PHP life cycle in webserver is doable I guess.

More over only the bit-array, m, k and hash are required to be persisted between sessions as far as i know. Why do we need the n value persisted?

To me you can just skip the semantics  (FS/DB) of storing BF instance and just implement a export and constructor with a json representation of the BF.

**Comment by praveenbm5** [comment]
Tested on PHP 5.3.8 Windows/Apache

Results:

Allocated 16777216 bits (2 MBytes)
Allocated 6 hashes
Contains 1000000 elements
Capacity of 1,750,350 (p=0.01)

Create Time: 0.035380125045776
Add Time: 71.28932094574 (14027 i/s)
Check Time: 47.939713954926 (20859 i/s)
500382

**Comment by praveenbm5** [comment]
When I use the MEM - 2: Division by zero in C:\www\php-bloom-filter\bloomfilter.php on 110

**Comment by dsx724** [comment]
MEM requires 2.1GB of RAM or more due to the way str_repeat and assignment works.  It tries to allocate a 1GB data structure that is then copied to the variable.

What's ur memory_limit?

**Comment by dsx724** [comment]
If you could, can u do add bunch of vardumps of the variables around that line?

**Comment by praveenbm5** [comment]
Here are the results of the test you asked.

I added var_dump on line 110 of bloomfilter.php

code:

var_dump($M, $magnitude, $unit);

output:

int 0
float -INF
string '' (length=0)

2: Division by zero in C:\www\php-bloom-filter\bloomfilter.php on 111 

code - $M /= pow(1024,$magnitude);

The memory limit on my php is 128MB.

**Comment by dsx724** [comment]
Check your error logs.  The MEM test tries to allocate 1GB.  It probably silently failed for some reason.
