### ISSUE TITLE
Change license from BSD-4-Clause to BSD-3-Clause or other.

### ISSUE THREAD

**Issue by cabello** [dsx724/php-bloom-filter#3]
Hi,

This clause: 

```
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product includes software developed by Da Xue.
```

Is very open, we won't be advertising that we have bloom filters on our project anywhere, but still this clause make us thing whether or not we should use the code.

As you can see on [Wikipedia article about BSD License](http://en.wikipedia.org/wiki/BSD_licenses), this license is old too.

Would you mind to review the software license please?

**Comment by dsx724** [comment]
I changed the license terms.  Thanks for bringing this to my attention.
